import test from 'node:test';
import assert from 'node:assert/strict';
import {EDGES,emptyBoard,applyPair,legalMoves,paletteCosts,graphFromBoard,inspectColouring,solveGraph,solveBoard,randomCompletion,seededRandom,choosePair,canonicalKey} from '../dist/engine.js';
import {newGame,whitePlayer,activePlayer,commitPair,applyColouring,paintCountry,finishRound,nextRound,undo,restoreGame} from '../dist/game.js';
const complete=n=>Array.from({length:n},(_,v)=>((1<<n)-1)^(1<<v));
// Independent fixed-order exhaustive oracle, without DSATUR or production pruning.
function oracle(adj,weights,costs){const cs=Array(adj.length).fill(-1);let best=Infinity;function visit(v,score){if(score>=best)return;if(v===adj.length){best=score;return;}for(let c=0;c<costs.length;c++){let ok=true;for(let u=0;u<v;u++)if((adj[v]&(1<<u))&&cs[u]===c){ok=false;break;}if(ok){cs[v]=c;visit(v+1,score+weights[v]*costs[c]);cs[v]=-1;}}}visit(0,0);return best;}
test('grid uses 40 shared sides, never diagonals or row wrapping',()=>{assert.equal(EDGES.length,40);assert(!EDGES.some(([a,b])=>a===4&&b===5));assert(!EDGES.some(([a,b])=>a===0&&b===6));});
test('any pair allowed; turn labels, singleton and illegal moves',()=>{let b=emptyBoard();assert.equal(legalMoves(b).length,300);b=applyPair(b,[0,24]);assert.equal(b[24],0);assert.throws(()=>applyPair(b,[0,1]));assert.throws(()=>applyPair(b,[1,1]));while(b.includes(-1))b=applyPair(b,legalMoves(b)[0]);const {adj,weights}=graphFromBoard(b);assert.deepEqual(weights,[...Array(12).fill(2),1]);adj.forEach((a,i)=>assert.equal(a&(1<<i),0));assert.throws(()=>applyPair(b,[0,1]));});
test('cliques force paid colours, charging the singleton only once',()=>{assert.equal(solveGraph(complete(3),[2,2,2]).penalty,0);assert.equal(solveGraph(complete(4),[2,2,2,2]).penalty,2);assert.equal(solveGraph(complete(4),[2,2,2,1]).penalty,1);assert.equal(solveGraph(complete(5),[2,2,2,2,2]).penalty,12);assert.equal(solveGraph(complete(6),Array(6).fill(2)).penalty,62);assert.equal(solveGraph(complete(6),[2,2,2,2,2,1]).penalty,37);});
test('exact weighted solver agrees with exhaustive oracle on 120 random graphs',()=>{const rng=seededRandom(928);for(let trial=0;trial<120;trial++){const n=4+trial%4,adj=Array(n).fill(0),weights=Array.from({length:n},()=>rng()<.25?1:2);for(let i=0;i<n;i++)for(let j=i+1;j<n;j++)if(rng()<.55){adj[i]|=1<<j;adj[j]|=1<<i;}const c=paletteCosts(),s=solveGraph(adj,weights,c);assert.equal(s.penalty,oracle(adj,weights,c.slice(0,n)),`trial ${trial}`);assert(s.optimal);}});
test('2,000 completed Gomulda maps return legal, correctly scored optima',()=>{const rng=seededRandom(222);for(let i=0;i<2000;i++){const b=randomCompletion(emptyBoard(),rng),s=solveBoard(b),info=inspectColouring(b,s.colours);assert(s.optimal);assert(info.valid);assert.equal(info.penalty,s.penalty);}});
test('conflicts rejected, paired colour is shared, red/black per-square scoring',()=>{const b=randomCompletion(emptyBoard(),seededRandom(42));const colours=Array.from({length:13},(_,i)=>i);assert(inspectColouring(b,colours).valid);const c=Array(13).fill(-1);c[0]=3;c[12]=4;assert.equal(inspectColouring(b,c).penalty,7);assert(!inspectColouring(b,c).valid);assert(inspectColouring(b,Array(13).fill(0)).conflicts.length>0);});
test('exact pairing endgame agrees with independent exhaustive minimax',()=>{const rng=seededRandom(700);function minimax(b){if(!b.includes(-1))return solveBoard(b).penalty;const vals=legalMoves(b).map(m=>minimax(applyPair(b,m)));const turn=(b.filter(x=>x>=0).length/2)%2;return turn===0?Math.max(...vals):Math.min(...vals);}for(let i=0;i<12;i++){const n=i%2?9:10,b=randomCompletion(emptyBoard(),rng).map(c=>c<n?c:-1),s=choosePair(b,{timeMs:5000,seed:i});assert(s.exact);assert.equal(s.maxExactDepth,12-n);assert.equal(s.maxTreeDepth,0);assert.equal(s.remainingPlies,12-n);assert.equal(s.value,minimax(b));assert.equal(minimax(applyPair(b,s.move)),s.value);}});
test('early search is legal and labels estimates honestly',()=>{const b=emptyBoard(),s=choosePair(b,{timeMs:40,seed:1});assert(!s.exact);assert(s.evaluated>0);assert.equal(s.budgetMs,40);assert.equal(s.remainingPlies,12);assert(s.maxTreeDepth>=1&&s.maxTreeDepth<=12);assert.equal(s.maxExactDepth,0);assert.doesNotThrow(()=>applyPair(b,s.move));});
test('board symmetries and country relabelling preserve position keys',()=>{const b=applyPair(applyPair(emptyBoard(),[0,4]),[5,8]);assert.equal(canonicalKey(b),canonicalKey(b.slice().reverse()));assert.equal(canonicalKey(b),canonicalKey(b.map(c=>c<0?c:1-c)));});
test('two rounds score White, switch roles, reset board and preserve score',()=>{const g=newGame({mode:'local',firstWhite:1});assert.equal(whitePlayer(g),1);assert.equal(activePlayer(g),1);assert.throws(()=>paintCountry(g,0,0));for(let r=1;r<=2;r++){for(let i=0;i<12;i++)commitPair(g,legalMoves(g.board)[0]);assert.equal(g.phase,'colour');assert.equal(activePlayer(g),1-whitePlayer(g));assert.throws(()=>finishRound(g));const solution=solveBoard(g.board);applyColouring(g,solution.colours);finishRound(g);assert.equal(g.scores[whitePlayer(g)],solution.penalty);if(r===1){assert.equal(g.phase,'roundEnd');nextRound(g);assert.equal(g.round,2);assert.equal(whitePlayer(g),0);assert(g.board.every(c=>c===-1));}}assert.equal(g.phase,'matchEnd');assert.equal(g.roundRecords.length,2);assert.throws(()=>finishRound(g));assert.deepEqual(restoreGame(JSON.stringify(g)),g);});
test('undo cancels a full AI reply and handles the phase transition',()=>{const g=newGame();commitPair(g,[0,1]);commitPair(g,[2,3]);assert(undo(g));assert(g.board.every(c=>c===-1));for(let i=0;i<12;i++)commitPair(g,legalMoves(g.board)[0]);assert.equal(g.phase,'colour');assert(undo(g));assert.equal(g.phase,'pair');assert.equal(g.board.filter(c=>c>=0).length,20);assert.equal(activePlayer(g),0);});
test('pencil notes never affect phase-two scoring; restore rejects corruption',()=>{const g=newGame();g.pencils.fill(4);for(let i=0;i<12;i++)commitPair(g,legalMoves(g.board)[0]);assert(g.pencils.every(c=>c===-1));assert(g.colours.every(c=>c===-1));assert.throws(()=>restoreGame('{bad'));assert.throws(()=>restoreGame(JSON.stringify({...g,board:[0]})));assert.throws(()=>paletteCosts(5));});
